selected_regions: ["TREx4l.*n_mu.*",
                  "TREx4l.*n_el.*",
                  "TREx4l.*n_jet.*",
                  "TREx4l.*n_bjet.*",
                  "TREx4l.*bjet0_pt.*",
                  "TREx4l.*bjet1_pt.*",
                  "TREx4l.*leading_GN2_quantile.*",
                  "TREx4l.*subleading_GN2_score.*",
                  "TREx4l.*met_met.*",
                  "TREx4l.*ttbar_mass.*",
                  "TREx4l.*ttz_score_onnx.*"] # This allows to filter which regions + variable pairs are used.

Job: # This corresponds to TREx settings.
  Label: ttZ
  CmeLabel: 13.6
  LumiLabel: 29.0

Fit: # This corresponds to TREx settings.
  FitType: "SPLUSB"
  FitRegion: "CRSR"
  POIAsimov: 1
  FitBlind: "True"

samples: # Sample settings. They need to match the ones defined in ttZconfig.yaml
    - name: "data"
      Color: 1
      Title: "Data"
      Type: "DATA"
    - name: "ttll"
      Color: 4 # You can define the sample colour, title and type.
      Title: "t#bar{t}Z"
      Type: "SIGNAL"
    - name: "tWZ"
      Color: 3
      Title: "tWZ"
      Type: "BACKGROUND"
    - name: "ZZ4ljj"
      Color: 2
      Title: "ZZ4ljj"
      Type: "BACKGROUND"
    - name: "ZZ4l"
      Color: 46
      Title: "ZZ4l"
      Type: "BACKGROUND"

Regions: # This block helps to overwrite options in specifc regions.
  - name: TREx4l.*
    Type: "VALIDATION" # For example this,
  - name: TREx4l.*ttz_score_onnx.*
    Type: "SIGNAL"
    Rebin: 10 # or this.
  - name: TREx4l.*bjet0_pt.*
    Type: "VALIDATION"
  - name: TREx4l.*bjet1_pt.*
    Type: "VALIDATION"
  - name: TREx4l.*met_met.*
    Type: "VALIDATION"
    VariableTitle: "E_{T}^{miss} [GeV]" # or this.
  - name: TREx4l.*ttbar_mass.*
    Type: "VALIDATION"

Systematics:
    - name: "Luminosity"
      Title: "Luminosity"
      Type: "OVERALL"
      OverallUp: 0.017
      OverallDown: -0.017
      Category: "Instrumental"

NormFactors: # We can attach normalisation factors to the samples.
    - name: "mu_signal"
      Title: "#mu(signal)"
      Nominal: 1
      Min: -100
      Max: 100
      Samples: "ttll"
    
    - name: "mu_bkg"
      Title: "#mu(bkg)"
      Nominal: 1
      Min: -100
      Max: 100
      Samples: "tWZ,ZZ4ljj,ZZ4l"
